[[DocType]]
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
[[PageTitle]]
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="content-language" content="en" />
<link href="[[SitePath]]styles/base.css" rel="stylesheet" type="text/css" />
[[Styles:File=jqueryui.css]]
<link rel="Shortcut Icon" href="./images/favicon.ico" />
</head>
<body>

[[Section:Name=Main]]

[[Scripts:File=jquery]]
</body>
</html>